name: 'WaitForURLsToBeAvailable'
description: 'Pause a CI workflow until a set of URLs become available'
author: "Vilius Sutkus '89"
inputs:
  URLs:
    required: true
    description: 'JSON encoded array of URLs to be checked'

  timeoutSeconds:
    required: false
    description: 'How long to wait after a failed check before retrying?'
    default: '60'

  tryCount:
    required: false
    description: 'How many times to try checking before assuming failure?'
    default: '20'

runs:
  using: 'node12'
  main: 'dist/index.js'

branding:
  icon: 'activity'
  color: 'green'
