name: 'build'
on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - run: npm ci
      - run: npm run all

      - name: Check if rebuild is needed
        run: git diff --exit-code dist
